---
d6c2de5d-ef90-45d1-82d4-5f2438369eea:
  title: Brexit
  children:
    634fd193-8039-4a70-a059-919c34ff4bfc:
      title: 'Brexit: business guidance'
    614b2e65-56ac-4f8d-bb9c-d1a14167ba25:
      title: 'Brexit: guidance for individuals'
495afdb6-47be-4df1-8b38-91c8adb1eefc:
  title: Business and industry
  children:
    13fb7519-c48e-4577-90f8-aaf483fa0c03:
      title: Business and the environment
    33bc0eed-62c7-4b0b-9a93-626c9e10c025:
      title: Business regulation
    80cb30f4-0361-49ea-ad84-bc10910318bf:
      title: Charities and social enterprises
    544a5fe2-b97c-4239-a6be-620469146a8b:
      title: Corporate governance
    d7e02519-b7ba-4297-80a8-01cd0e5f2cb2:
      title: Financial services
    74f7449e-08f8-4325-b8db-3703cb99f4d0:
      title: Industrial strategy
    d34ba9b3-28d8-40d5-a2d3-f52d216c2590:
      title: Manufacturing
    4ef6d013-ec2d-4ae8-a1a0-5a984e6e6c42:
      title: Media and communications
    8aa41155-58ff-4d7d-a11a-7e3ef42863dd:
      title: Running a business
    ccb77bcc-56b4-419a-b5ce-f7c2234e0546:
      title: Science and innovation
    ed2ca1f7-5463-4eda-9324-b597e269e242:
      title: Trade and investment
    a1e4659c-dc15-48be-bc4f-6c609ae061dc:
      title: UK economy
5b7b9532-a775-4bd2-a3aa-6ce380184b6c:
  title: COVID-19
  children:
    14e7aabf-97c7-4b33-941d-4dda274f793e:
      title: Driving and transport in the UK during COVID-19
    272308f4-05c8-4d0d-abc7-b7c2e3ccd249:
      title: Education, universities and childcare during COVID-19
    0f3357e6-23ae-4ad2-9d31-a55a72cbb227:
      title: Health and wellbeing during COVID-19
    c2bbb66f-b108-4147-8db1-c637d0d28790:
      title: Healthcare workers, carers and care settings during COVID-19
    2f386752-3743-47a8-ae66-110131cf96aa:
      title: Housing and accommodation during COVID-19
    c7dbc2d2-d070-4315-952a-fb77faa78021:
      title: International travel, immigration and repatriation during COVID-19
    5c37c642-d4dc-43ff-a7af-3fb30e18c642:
      title: Rules and restrictions during COVID-19
    65666cdf-b177-4d79-9687-b9c32805e450:
      title: Support for businesses and self-employed people during COVID-19
    b9ade971-9c53-4318-b95b-906a122ed2f8:
      title: Testing for COVID-19
    bfcbc853-d88d-4d79-9a48-a797a4e59a03:
      title: Vaccinations for COVID-19
    fa584e4c-8be1-418c-babe-1e3e0c64ebee:
      title: Volunteering and offering help during COVID-19
    b7f57213-4b16-446d-8ded-81955d782680:
      title: Work and financial support during COVID-19
a544d48b-1e9e-47fb-b427-7a987c658c14:
  title: Corporate information
  children: {}
ba951b09-5146-43be-87af-44075eac3ae9:
  title: Crime, justice and law
  children:
    66f7bd95-7e8b-4f33-ad7f-77a13ae92d49:
      title: Administrative justice reform
    15492103-227c-47c4-bb98-0380458b81df:
      title: Attorney General guidance to the legal profession
    562132d3-7f14-46e8-953b-d7e0d56cf021:
      title: Byelaws
    7ed17bb3-42cd-432a-80fa-c4ee82ad4f2a:
      title: Civil justice reform
    58643944-9cc3-4f61-8805-4c1d090bf21d:
      title: 'Counter-extremism '
    165bfd10-8402-4719-b38e-62ca618d3b8f:
      title: Counter-terrorism
    357110bb-cbc5-4708-9711-1b26e6c63e86:
      title: Courts, sentencing and tribunals
    7f4eaf37-60f8-4d8c-a968-7829098e05ff:
      title: Crime prevention
    23100f5c-25d2-4d3f-8a63-f32e619a32d5:
      title: Criminal justice reform
    6cbc4c56-f412-4116-bd2f-66dfbdcd94ae:
      title: Criminal record disclosure
    17b10a3e-2530-49cc-8cf6-1e002458b0b0:
      title: Data protection
    a15cc825-5319-40a9-8396-0153920f8f0b:
      title: Domestic violence
    fae66b20-eacd-4a41-a417-81cae5fa4b8c:
      title: Family justice system
    783cf728-cd63-47ce-aa63-b466b2ea3982:
      title: Forced marriage
    afd65c1c-dee0-4f5b-8bd6-4f502e4870af:
      title: Justice system transparency
    587fd3ee-c009-4a49-8b30-557300c55bd1:
      title: Knife, gun and gang crime
    cade4e7d-0397-459d-a880-3d2753dd39c2:
      title: Law and practice
    4919a97c-3249-496c-8485-b7c8d36d6ef0:
      title: Legal aid
    1906f68c-2d10-4182-9a0f-31a1f7d77c29:
      title: Legal aid reform
    ff10faa5-1bc0-41a4-8629-d528915ad7e4:
      title: Policing
    1dd3f25a-9237-4143-b2d2-cd7f6863c9c0:
      title: Prisons and probation
    459b36eb-65f0-43a6-95ab-f3fb0bdaff50:
      title: Reoffending and rehabilitation
    fa5b3b7e-682a-49fd-bf99-d2cfe3e16a26:
      title: Reporting crimes and getting compensation
    70505387-138c-431c-a82d-94ff81f97e18:
      title: Sentencing reform
    e9926d96-9bfd-4d8f-ad4e-301254216298:
      title: Statutory rights
    d1b7471b-bdd1-4719-9376-b79d2f854807:
      title: Victims of crime
    756613a3-522d-4402-beb9-532b5708ba74:
      title: Violence against women and girls
    1fb1ae8d-c975-43ba-9672-13ee0993e98b:
      title: Young people and the law
    ed952e5a-2ea7-44c0-aed9-c97ffe58993b:
      title: Your rights and the law
e491505c-77ae-45b2-84be-8c94b94f6a2b:
  title: Defence and armed forces
  children:
    268c139d-8d58-43ed-85f4-19c511e283e7:
      title: Armed Forces Covenant
    8ff8cf05-a6e6-4757-a896-4fabd9f3229a:
      title: Armed forces
    8f589b76-f3ee-4eca-adf6-2ad70807ad8c:
      title: Armed forces and Ministry of Defence reform
    253c217e-5d8e-4ec6-acfb-e5165674cac5:
      title: Armed forces support for activities in the UK
    9f183c2c-2256-42d7-a12d-ced7b7f24195:
      title: International defence commitments
    72241f43-600b-4c34-9205-5a07060a2711:
      title: Military awards and commemorations
    ac5d432a-11a9-40e1-bb83-0de26106b9d6:
      title: Military equipment, logistics and technology
    4b9f1f6f-0c16-4a99-94e5-e58a3fba461f:
      title: Military recruitment, training and operations
    e33ce727-bb6b-47a2-894b-b7174cb7faee:
      title: Ministry of Defence estate
    45c29c6b-1bc4-4b3b-af9d-0d05e019269d:
      title: Nuclear disarmament
    735f4865-8b48-4ea8-99c2-94f121839367:
      title: Stability in the Western Balkans
    e4b9e05a-6c04-4e18-945f-4584c08c4628:
      title: Support services for military and defence personnel and their families
    d6fc8b39-351d-4d3f-a938-4a86f38906bc:
      title: UK nuclear deterrent
    1f21cce7-fc86-433c-a79b-1a4f0acb5a3a:
      title: Veterans and family support
    761b3ded-bc40-498e-8964-d31c9664970a:
      title: Weapons proliferation
c58fdadd-7743-46d6-9629-90bb3ccc4ef0:
  title: Education, training and skills
  children:
    d2005b89-352f-4896-aced-1d17504330e6:
      title: Education of disadvantaged children
    23265b25-7ec3-4960-8517-4ff8d4d92cac:
      title: Funding and finance for students
    dd767840-363e-43ad-8835-c9ab516633de:
      title: Further and higher education, skills and vocational training
    f0dcb0b9-2f2c-46b0-adea-42a4fe608170:
      title: Inspections and performance of education providers
    db605204-0f03-441b-837f-16613c6b3f8f:
      title: Pupil wellbeing, behaviour and attendance
    42e6e5c3-3a06-4a6f-abd4-a4b85d9c6b16:
      title: Running and managing a school
    1a26ae19-00f2-4be1-b9b6-aa72876a0278:
      title: School and academy financial management and assurance
    90e8a226-8d40-4c1f-91e4-36a712b34e57:
      title: School and academy funding
    7c75c541-403f-4cb1-9b34-4ddde816a80d:
      title: School curriculum
    47b6ce42-0bfa-42ee-9ff1-7a9c71ee9727:
      title: Special educational needs and disability (SEND) and high needs
    a8bffaae-5c8c-439f-92f0-c9fbf32ce1d9:
      title: Starting and attending school
    ff00b8b2-dcdb-4659-93c2-291c9be354f3:
      title: Teaching and leadership
ba3a9702-da22-487f-86c1-8334a730e559:
  title: Entering and staying in the UK
  children:
    262e9ea7-90fc-4ac8-8aa7-fc294282a1d4:
      title: Border control
    6dc91505-fdbd-4b6b-9bd5-fef3dc8baf42:
      title: Immigration adviser services
    fa13521f-9285-45b0-bd65-4a472a8037e7:
      title: Immigration offences
    c64eb759-93ff-4bfd-86f2-16753fc1e062:
      title: Immigration rules
    0fab9131-f877-4286-b4d8-922fbfb402b6:
      title: Inspections of border, immigration and asylum services
    fef7e737-6f1a-4ef4-b844-aa24b630ad03:
      title: Permanent stay in the UK
    '08a8a69f-2825-4fe2-a4cf-c83458a5629e':
      title: Refugees, asylum and human rights
    6e85c12f-f52b-41b3-93ad-59e5f19d64f6:
      title: Rights of foreign nationals in the UK
    18c7918f-cde5-4e66-b5f4-cd15c33cc1cc:
      title: Travel and identity documents for foreign nationals
    29480b00-dc4d-49a0-b48c-25dda8569325:
      title: Visas and entry clearance
    f48188df-8130-4d36-98e0-e72125d016a2:
      title: Visas and immigration corporate
3cf97f69-84de-41ae-bc7b-7e2cc238fa58:
  title: Environment
  children:
    22ad4441-9fb5-447b-950c-bf33466b31bb:
      title: Chemicals
    62e08e6f-9161-42c6-b9dd-0cf8fcab2c69:
      title: Climate change and energy
    b14a6778-60a2-483a-924c-774d1040cbf4:
      title: Commercial fishing, fisheries and vessels
    899d76d6-4d59-409e-a7a4-2a7e47c9361b:
      title: Energy infrastructure
    4e561949-4a26-49c2-918d-6ad2972c4d33:
      title: Environmental permits
    52ff5c99-a17b-42c4-a9d7-2cc92cccca39:
      title: Food and farming
    42fdd045-cadf-474b-b8a6-ca20a77c43bb:
      title: Marine
    a1efce91-28c3-4a33-a2fd-48364b1119a4:
      title: Pollution and environmental quality
    71f685fe-0dc3-469d-92c2-1000ad86d7d9:
      title: River maintenance, flooding and coastal erosion
    9949c2c1-ff96-4b4f-b584-c700e316c9de:
      title: Rural and countryside
    f4e9e92d-9192-4e17-90c6-553339bc04c3:
      title: Waste and recycling
    cb4c8377-6fcb-4022-a7a1-98395eb50508:
      title: Water industry
    695dc6f2-27cc-4d8b-adc4-8d07c2bff748:
      title: Wildlife, animals, biodiversity and ecosystems
9597c30a-605a-4e36-8bc1-47e5cdae41b3:
  title: Going and being abroad
  children:
    3dbeb4a3-33c0-4bda-bd21-b721b0f8736f:
      title: British nationals overseas
    d956c72a-246d-4787-af39-00bf58b2ea66:
      title: Living abroad
    27b9c5cd-b390-4332-89be-73491df35a41:
      title: Passports
    d96e4efc-9c26-4d9b-9fa7-a036b5c11a65:
      title: Travel abroad
e48ab80a-de80-4e83-bf59-26316856a5f9:
  title: Government
  children:
    67f50352-bc30-482f-a2d0-a05714e3cea8:
      title: Cyber security
    b7374969-dfdf-46eb-97f3-7772c011c10d:
      title: Data
    95d06252-5d75-42fb-9c5c-038ab6b482e4:
      title: Democracy
    78c2148c-a7cd-448b-8105-9f78ded119d1:
      title: Emergency preparation, response and recovery
    3afd1d79-597d-4f97-bc7a-83766dcab2f4:
      title: Europe
    f3f4b5d3-49c4-487b-bd5b-be75f11ec8c5:
      title: Government efficiency, transparency and accountability
    dfe808c3-6a58-4266-8f50-a93d931bfaaf:
      title: 'Government reform '
    90c9b9f1-0a4f-4639-b1e9-2bfb23d611bd:
      title: Government technology and digital services
    8a98b827-82ad-49b4-819e-82c208c551c4:
      title: National security
    ccd41790-a498-4cd1-a510-125d67e0f585:
      title: Public sector land use
    383f2d71-b239-4d90-b89b-600340b34332:
      title: Public services
    3894b4d1-bb7f-4c3d-a680-c904ccabd91e:
      title: Sustainable development
8124ead8-8ebc-4faf-88ad-dd5cbcc92ba8:
  title: Health and social care
  children:
    c50bd0f5-3077-43cc-8500-8e68b67c8b79:
      title: Blood regulation and safety
    d69977ab-4fb1-4ad6-b379-e967c5b7528b:
      title: Disabled people
    cebc01ee-f70a-4397-a552-622e10b62508:
      title: Medicines, medical devices
    f3dcc290-752f-4bbe-b379-9155d919a58d:
      title: National Health Service
    d6a4884e-769d-4b81-8ba5-b64394362d92:
      title: Public health
    2eb09bb6-b069-4604-a55a-08e6cd46d257:
      title: Research and innovation in health and social care
    7d67047c-bf22-4c34-b566-b46d6973f961:
      title: Social care
    88c55513-b473-4627-a856-6ae95b6b4e08:
      title: Technology in health and social care
4794066e-e3cc-425e-8cc4-e7ff3edb4c39:
  title: Housing, local and community
  children:
    6bb7a2d2-1693-4682-a52c-a17d7fca9c3e:
      title: Household energy
    4ad66168-274d-4d83-9195-f4ab0ccc97cb:
      title: Housing and communities
    82730dd2-4ead-4ae6-943b-2c910e758279:
      title: Land registration
    e3147d4f-4bd5-4a14-a386-4ba7ccb058b4:
      title: Planning and building
37d0fa26-abed-4c74-8835-b3b51ae1c8b2:
  title: International
  children:
    b1c19cf1-7533-480b-97e2-ab4c4812c7fa:
      title: Anti-corruption
    d6dba75a-42bd-4e1e-984c-2bddb6b41951:
      title: Foreign affairs
    cb7db7bb-d0b4-4e22-9f0b-58a28c2db38c:
      title: Human rights internationally
    9fb30a53-70fb-4f1c-878b-0064b202d1ba:
      title: International aid and development
    c7fded2a-fedc-4977-be5d-efd4f6a34a73:
      title: Sexual violence in conflict
    6a10a7ae-4729-4941-9889-c2330b6a893b:
      title: The Commonwealth
    d376bc0d-6c47-4399-b1bf-d9adefa47df0:
      title: 'UK prosperity and security: Asia, Latin America and Africa'
20086ead-41fc-49cf-8a62-d4e1126f41fc:
  title: Life circumstances
  children:
    f875c256-b84a-417a-b2b5-ff7e301a41c7:
      title: Certificates, register offices, changes of name or gender
    0fffa994-b76d-4539-8bf9-2a6c6751580d:
      title: Death and bereavement
    0a018d28-e3a8-4db7-a593-c8a0bfb57319:
      title: Having a child, parenting and adoption
    6bf58181-7ebe-4599-8a93-281f9b7af810:
      title: Lasting power of attorney, being in care and managing finances
    fe0b40e6-f742-45b0-9b2c-2cb976ce18ad:
      title: Marriage, civil partnership and divorce
    ab663472-1f7b-473c-ac15-e433ff9bd7e6:
      title: Missing persons
6acc9db4-780e-4a46-92b4-1812e3c2c48a:
  title: Money
  children:
    28262ae3-599c-4259-ae30-3c83a5ec02a1:
      title: Business tax
    7c4cf197-2dba-4a82-83e2-6c8bb332525c:
      title: Court claims, debt and bankruptcy
    b20215a9-25fb-4fa6-80a3-42e23f5352c2:
      title: Dealing with HMRC
    5605545e-03ca-4520-9519-163ea341bc86:
      title: Expenses and employee benefits
    a7b67f4f-1234-4a0c-90ba-eeed4c5183cd:
      title: Money laundering regulations
    a5c88a77-03ba-4100-bd33-7ee2ce602dc8:
      title: Personal tax
    35136812-221c-4ba2-8ed1-46e409ca5e10:
      title: Tax evasion and avoidance
206b7f3a-49b5-476f-af0f-fd27e2a68473:
  title: 'Parenting, childcare and children''s services '
  children:
    5a9e6b26-ae64-4129-93ee-968028381e83:
      title: Adoption, fostering and surrogacy
    f1d9c348-5c5e-4fc6-9172-13a62537d3ae:
      title: Childcare and early years
    2389dfd4-a0c4-4bd2-b7e6-06f465463d22:
      title: Children's health and welfare
    1423ec9f-d62c-40f7-b10e-a2bdf020d8b7:
      title: Divorce, separation and legal issues
    a44b1c68-807c-45fe-bc7b-a47586617863:
      title: Financial help if you have children
    e4335adc-5dc3-47c0-bb27-4998792212eb:
      title: Pregnancy and birth
    20eb4e84-98ee-404b-a4bd-fe8a36d5d71d:
      title: Safeguarding and social care for children
    43fcdde6-59c5-487f-a969-a046b334cbec:
      title: Youth employment and social issues
503c5bc7-809a-47b9-83e2-bd0c212dbabb:
  title: Regional and local government
  children:
    f2c9ec1e-bbdd-45b8-afd7-fab0c9371d4b:
      title: Devolution
    15191831-40b4-4f6e-ade3-e82d7c775afd:
      title: Local councils and services
    c914fd40-dd0a-45c4-a6ff-bce0cda31bde:
      title: Local government
    3b643153-c4ff-45aa-b923-0be70b083071:
      title: Local government spending
    88b0ec49-b8fc-4fbb-8418-68b88719b8c8:
      title: Localism
    a1e624ed-e268-44ab-ac3f-4d3cb2bb8cb5:
      title: Northern Ireland
    e2aac912-93c5-4b19-bd3d-9c12676e985c:
      title: Scotland
    68ad6c84-49fd-4871-95bc-5bd48c0f81e1:
      title: Wales
e2ca2f1a-0ff3-43ce-b813-16645ff27904:
  title: Society and culture
  children:
    b29cf14b-54c6-402c-a9f0-77218602d1af:
      title: Arts and culture
    0d74fa5d-e56e-4765-904e-2337fa46218e:
      title: 'British citizenship '
    0bb6e269-4c6d-432d-96b6-f2b343a7603c:
      title: Charities, volunteering and honours
    668cd623-c7a8-4159-9575-90caac36d4b4:
      title: Community and society
    16bb50c0-2ca2-49e9-8b21-088789e66d5e:
      title: Digital inclusion and accessibility in society
    b297e49c-7da4-4bc1-8714-da80fa0758d3:
      title: Equality, rights and citizenship
    2e444a6b-c6b5-4c7b-a66a-d7e059914979:
      title: Loneliness
    3506d46e-62d7-4602-93f5-fcb9bb2aade8:
      title: National events and ceremonies
    ecc8978c-cc6b-463e-a3d5-d5428c3e9f7d:
      title: Online safety
    f9e476ef-654d-41ec-97d9-2b6842d4361d:
      title: Sports and leisure
    96c479bc-9b6c-49d3-8e86-3821f43a6fb0:
      title: Tourism
    ae747de8-96ad-4f66-9d6d-4d5c357e9956:
      title: Young people
a4038b29-b332-4f13-98b1-1c9709e216bc:
  title: Transport
  children:
    51efa3dd-e9bc-42b2-aa26-06bf5f543015:
      title: Aviation
    3767d89c-b00c-431e-8b0b-b91c8ff26238:
      title: Careers in transport
    d39a3eae-b358-4472-83e2-2e17a86e2ad8:
      title: Corporate and operational information (transport)
    84a394d2-b388-4e4e-904e-136ca3f5dd7d:
      title: Driving and road transport
    3e4df71e-474d-4a40-bd6a-b3072affa151:
      title: Freight, haulage and cargo
    3b4d6319-fcef-4637-b35a-e3df76321894:
      title: Local transport
    4a9ab4d7-0d03-4c61-9e16-47787cbf53cd:
      title: Maritime and shipping
    13d01427-33b5-4ca4-bf7a-68425f54e236:
      title: Rail
    95202728-fb55-4aac-a53e-6a8f1553348a:
      title: Road infrastructure
    4d72b9fa-a11a-485e-9c22-8fb426e0feaa:
      title: Transport accessibility and disability
    230a94c8-362a-4e3f-9a83-823472aa202a:
      title: Transport modelling and appraisal
    82e9e133-20aa-424d-bc61-f30b29e2d05b:
      title: Transport planning
    02a5bdc0-9a62-4286-9128-c923845fa1c5:
      title: Transport security
dded88e2-f92e-424f-b73e-6ad24a839c51:
  title: Welfare
  children:
    536f83c0-8c67-47a3-88a4-d5b1eda591ed:
      title: Benefits entitlement
    29dbee2a-5865-489b-860f-7eef54a5165a:
      title: Benefits for families
    05a9527b-e6e9-4a68-8dd7-7d84e6a24eef:
      title: Carers and disability benefits
    7a1ba896-b85a-4137-81d9-ab05b7ce67dd:
      title: Child Benefit
    a4822791-855a-4f14-877a-e199b5c58126:
      title: Child maintenance reform
    ac7b8472-5d09-4679-9551-87847b0ac827:
      title: Death and benefits
    6c4c443c-2e11-4d25-aa93-2e3a38d9499c:
      title: Heating and housing benefits
    2a1bd1b1-5025-4313-9e5b-8352dd46f1d6:
      title: Jobseeker's Allowance and low income benefits
    a7f3005b-a3cd-4060-a127-725accb54f2e:
      title: Tax credits
    62fcbba5-3a75-4d15-85a6-d8a80b03d57c:
      title: Universal Credit
    76b03d8c-e5cc-4ba0-8630-c7cc71fb87ad:
      title: Welfare reform
d0f1e5a3-c8f4-4780-8678-994f19104b21:
  title: Work
  children:
    0133b1b3-9ecd-48ad-b226-538b46a17ff4:
      title: Government graduate schemes
    b83f3fc7-4057-4aee-a9db-4d5fb8b49e2a:
      title: Health and safety at work
    36c7772d-f1ef-4506-a9af-be366bf49af4:
      title: Health and safety reform
    4c18a195-9b74-4882-8d11-bf224ceb8292:
      title: Labour market reform
    374b4837-cf2a-4529-a7f1-559d92b3d90d:
      title: Payroll
    6df55cf4-d25c-41d2-aec9-824c67a9eb51:
      title: Pensions and ageing society
    460718d9-82e4-40a7-bbe8-8824a4a05590:
      title: Secondments with government
    24e91c04-21cb-479a-8f23-df0eaab31788:
      title: Self-employment
    5f1f5537-e9e6-488d-85f6-bd91327987ec:
      title: Trade unions
    5b9686c9-eaf8-48bd-9351-5fac0e721a02:
      title: Work and disabled people
    '092348a4-b896-4f8f-a0dc-e6d4605a4904':
      title: Working, jobs and pensions
